In [ ]:
import numpy as np
def create_board():
  board=np.zeros((7,7))


  return board
board=create_board()
print(board)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
def create_board():
  board=np.zeros((7,7))
  return board
board=create_board()
def drop_piece(board,row,col,piece):
  board[row][col]=piece
def is_valid_location(board,col):
  return board[6][col]==0
def get_next_open_row(board,col):
  for r in range(7):
    if board[r][col]==0:
      return r
def print_board(board):
  print(np.flip(board,0))
  # for rows
def winning_move(board,piece):
  for c in range(4):
    for r in range(7):
      if board[r][c]==piece and board[r][c+1]==piece and board[r][c+2]==piece and board[r][c+3]==piece:
        return True
  # for columns
  for c in range(7):
    for r in range(4):
      if board[r][c]==piece and board[r+1][c]==piece and board[r+2][c]==piece and board[r+3][c]==piece:
        return True
  # for positively sloped diagonals
  for c in range(4):
    for r in range(4):
      if board[r][c]==piece and board[r+1][c+1]==piece and board[r+2][c+2]==piece and board[r+3][c+3]==piece:
        return True
  # for negatively sloped diagonals
  for c in range(4):
    for r in range(3,7):
      if board[r][c]==piece and board[r-1][c+1]==piece and board[r-2][c+2]==piece and board[r-3][c+3]==piece:
        return True
board=create_board()
print_board(board)
game_over=False
turn=0
while not game_over:
  if turn==0:
    col =int(input('player1(0,6):'))
    if is_valid_location(board,col):
      row=get_next_open_row(board,col)
      drop_piece(board,row,col,1)
      turn=1
      if winning_move(board,1):
        print('player 1 wins!!!! congrats')
        x=int(input('enter 0 to exit'))
        if x==0:
          break


  else:
    col=int(input('player2(0,6):'))
    if is_valid_location(board,col):
      row=get_next_open_row(board,col)
      drop_piece(board,row,col,2)
      turn=0

      if winning_move(board,2):
        print('player 2 wins!!!! congrats')
        x=int(input('enter 0 to exit'))
        if x==0:
          break
#game_over=True
print(board)
print_board(board)





[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
player1(0,6):1
player2(0,6):2
player1(0,6):1
player2(0,6):2
player1(0,6):1
player2(0,6):2
player1(0,6):1
player 1 wins!!!! congrats
enter 0 to exit0
[[0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
